part of 'main.dart';

class TripsPage extends StatefulWidget{const TripsPage({super.key});@override State<TripsPage> createState()=>_TripsPageState();}
class _TripsPageState extends State<TripsPage>{List<Map<String,dynamic>>rows=[],packages=[];@override void initState(){super.initState();load();}Future<void>load()async{final r=await Future.wait([Store.list('trips'),Store.list('packages')]);if(!mounted)return;setState((){rows=active(r[0]);packages=active(r[1]);});}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Viajes')),body:rows.isEmpty?const Center(child:Text('Aún no hay viajes.')):ListView.builder(itemCount:rows.length,itemBuilder:(_,i){final t=rows[i];final ids=dynList(t['packageIds']).map((e)=>'$e').toSet();final w=packages.where((p)=>ids.contains('${p['id']}')).fold<double>(0,(a,e)=>a+number(e['billWeight']));final income=w*number(t['ratePerLb']);final exp=tripExpenses(t);return ListTile(leading:const Icon(Icons.flight_takeoff),title:Text('${t['origin']} → ${t['destination']} · ${t['date']}'),subtitle:Text('${w.toStringAsFixed(1)} / ${number(t['capacityLb']).toStringAsFixed(1)} lb · Ganancia est.: ${money(income-exp)}'),onTap:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>TripEditPage(existing:t)));load();},trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{if(await confirmDelete(context,'este viaje')){await softDelete('trips','${t['id']}');load();}}));}),floatingActionButton:FloatingActionButton.extended(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const TripEditPage()));load();},icon:const Icon(Icons.add),label:const Text('Viaje')));}

double tripExpenses(Map<String,dynamic>t){final base=number(t['flightCost'])+number(t['bagsCost'])+number(t['transportCost'])+number(t['stayCost']);final other=dynList(t['otherExpenses']).fold<double>(0,(a,e)=>a+number((e as Map)['amount']));return base+other;}

class TripEditPage extends StatefulWidget{final Map<String,dynamic>?existing;const TripEditPage({super.key,this.existing});@override State<TripEditPage> createState()=>_TripEditPageState();}
class _TripEditPageState extends State<TripEditPage>{final origin=TextEditingController(),dest=TextEditingController(),date=TextEditingController(),capacity=TextEditingController(),rate=TextEditingController(),flight=TextEditingController(),bags=TextEditingController(),transport=TextEditingController(),stay=TextEditingController();List<Map<String,dynamic>>packages=[];Set<String>selected={};List<Map<String,dynamic>>other=[];bool loaded=false;
@override void initState(){super.initState();init();}Future<void>init()async{packages=active(await Store.list('packages'));final s=await Store.settings();origin.text='${widget.existing?['origin']??'FLL'}';dest.text='${widget.existing?['destination']??'HAV'}';date.text='${widget.existing?['date']??today()}';capacity.text='${widget.existing?['capacityLb']??180}';rate.text='${widget.existing?['ratePerLb']??s['ratePerLb']}';flight.text='${widget.existing?['flightCost']??0}';bags.text='${widget.existing?['bagsCost']??0}';transport.text='${widget.existing?['transportCost']??0}';stay.text='${widget.existing?['stayCost']??0}';selected=dynList(widget.existing?['packageIds']).map((e)=>'$e').toSet();other=dynList(widget.existing?['otherExpenses']).map((e)=>Map<String,dynamic>.from(e as Map)).toList();if(mounted)setState(()=>loaded=true);}
Future<void>addOther()async{final n=TextEditingController(),a=TextEditingController(),note=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Otro gasto'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Concepto')),const SizedBox(height:8),TextField(controller:a,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Monto')),const SizedBox(height:8),TextField(controller:note,decoration:const InputDecoration(labelText:'Notas'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Añadir'))]));if(ok==true&&n.text.trim().isNotEmpty&&number(a.text)>0)setState(()=>other.add({'id':newId(),'name':n.text.trim(),'amount':number(a.text),'notes':note.text.trim()}));}
Future<void>save()async{final rows=await Store.list('trips');final item={'id':widget.existing?['id']??newId(),'origin':origin.text.trim().toUpperCase(),'destination':dest.text.trim().toUpperCase(),'date':date.text.trim(),'capacityLb':number(capacity.text),'ratePerLb':number(rate.text),'flightCost':number(flight.text),'bagsCost':number(bags.text),'transportCost':number(transport.text),'stayCost':number(stay.text),'otherExpenses':other,'packageIds':selected.toList(),'deleted':false};final i=rows.indexWhere((e)=>e['id']==item['id']);if(i>=0)rows[i]={...rows[i],...item};else rows.add(item);await Store.saveList('trips',rows);if(mounted)Navigator.pop(context);}
@override Widget build(BuildContext context){if(!loaded)return const Scaffold(body:Center(child:CircularProgressIndicator()));final w=packages.where((p)=>selected.contains('${p['id']}')).fold<double>(0,(a,e)=>a+number(e['billWeight']));final income=w*number(rate.text);final temp={'flightCost':number(flight.text),'bagsCost':number(bags.text),'transportCost':number(transport.text),'stayCost':number(stay.text),'otherExpenses':other};final exp=tripExpenses(temp);return Scaffold(appBar:AppBar(title:Text(widget.existing==null?'Nuevo viaje':'Editar viaje')),body:ListView(padding:const EdgeInsets.all(16),children:[
Row(children:[Expanded(child:TextField(controller:origin,decoration:const InputDecoration(labelText:'Origen (FLL/MIA)'))),const SizedBox(width:8),Expanded(child:TextField(controller:dest,decoration:const InputDecoration(labelText:'Destino (HAV)')))]),const SizedBox(height:12),TextField(controller:date,decoration:const InputDecoration(labelText:'Fecha YYYY-MM-DD')),const SizedBox(height:12),Row(children:[Expanded(child:TextField(controller:capacity,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Capacidad lb'))),const SizedBox(width:8),Expanded(child:TextField(controller:rate,onChanged:(_)=>setState((){}),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Tarifa $/lb')))]),const SizedBox(height:16),
Text('Gastos',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),
TextField(controller:flight,onChanged:(_)=>setState((){}),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Vuelo')),const SizedBox(height:8),TextField(controller:bags,onChanged:(_)=>setState((){}),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Equipaje')),const SizedBox(height:8),TextField(controller:transport,onChanged:(_)=>setState((){}),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Transporte / gasolina')),const SizedBox(height:8),TextField(controller:stay,onChanged:(_)=>setState((){}),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Estancia')),const SizedBox(height:8),
for(final e in other)ListTile(contentPadding:EdgeInsets.zero,title:Text('${e['name']}'),subtitle:Text('${money(number(e['amount']))} · ${e['notes']}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>setState(()=>other.remove(e)))),Align(alignment:Alignment.centerLeft,child:TextButton.icon(onPressed:addOther,icon:const Icon(Icons.add),label:const Text('Añadir otro gasto'))),
const Divider(height:28),Text('Asignar paquetes',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),for(final p in packages.where((p)=>['Recibido','Verificado','Listo para Cuba','Asignado a viaje'].contains(p['status'])))CheckboxListTile(value:selected.contains('${p['id']}'),onChanged:(v)=>setState((){if(v==true)selected.add('${p['id']}');else selected.remove('${p['id']}');}),title:Text('${p['tracking']}'),subtitle:Text('${number(p['billWeight']).toStringAsFixed(1)} lb')),
const Divider(height:28),_sectionCard(context,'Rentabilidad estimada',Icons.calculate,[Text('Peso asignado: ${w.toStringAsFixed(1)} lb'),Text('Ingresos: ${money(income)}'),Text('Gastos: ${money(exp)}'),Text('Ganancia: ${money(income-exp)}',style:const TextStyle(fontWeight:FontWeight.bold))]),const SizedBox(height:14),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('Guardar viaje')),const SizedBox(height:60)]));}}
